### ISSUE TITLE
Instructions pdf does not align with repo content

### ISSUE THREAD

**Issue by michaeljquinn** [parasoft/docker#1]
The pdf refers to the "virtualize" component, which does not exist in the repo, i assume its soa-virt

Also, the soa-virt Dockerfile needs the datarepository image, ??, I assume I can use tomcat8 instead (if i dont need datarepo).  The problem with the virt-server zip (below) remains

Also some instructions on where to down load/locate the zip files referred to in the Dockerfiles (DataRepository.zip and parasoft_soavirt_server_9.10.3.zip) would be really useful.

Also, the pdf is based on a Virtualbox deploy, rather than an generic docker/linux approach.  Lots of refs to NAT/s etc which is applicable to a VB deploy, 

Also, I am happy to contrib the docker-compose files once I get the images building ok

**Comment by michaeljquinn** [comment]
Here is an update
The parasoft_soavirt_server_9.10.3.zip is found on the customer portal as the "WAR" deployment option
ie SOAtest/Virtualize - Platform All - Version 9.10-Installer Virtualise Server only (WAR deployment)

I must have missed those instructions on the pdf
cheers

**Comment by mattloveparasoft** [comment]
I updated the PDF instructions to match the layout of Dockerfiles in this repo.
Earlier the Dockerfiles were updated to download the required zips directly so you no longer need to look for them in the customer portal.
