### ISSUE TITLE
Dockerfile's cannot be built - Missing dependencies.

### ISSUE THREAD

**Issue by SailingYYC** [parasoft/docker#2]
The instructions are out of date, all of the `zip` file dependencies are missing, and the `Dockerfile`s are not consistent. I've updated all of the `Dockerfile`s so they function and can build automatically, as per the instructions.

Would you be interested in me putting in a pull request?

**Please be advised:** The updates I've made include links to automatically download the `zip` files from Parasoft's servers.

**Comment by SailingYYC** [comment]
@mattloveparasoft Any advice on how to proceed?

**Comment by mattloveparasoft** [comment]
Go ahead and submit a pull request.  I will review it.  Project management has given us the green light to share Parasoft download links in public Git Hub sources.

**Comment by SailingYYC** [comment]
Thanks @mattloveparasoft, I went to do one last run through last night before doing the PR, but noticed all the Parasoft downloads were getting 502 Bad Gateway errors. Today they're giving 404 Not Found errors. Were all of the assets relocated? No 302 Redirects?

**Comment by mattloveparasoft** [comment]
@SailingYYC  Can you share the URLs that are giving 404 Not Found errors?

**Comment by SailingYYC** [comment]
https://www1.parasoft.com/downloads/virtualize/parasoft_continuous_testing_platform_3.1.1.zip
https://www1.parasoft.com/downloads/virtualize/parasoft_data_repository_server_9.10_linux_x86_64.zip
https://www1.parasoft.com/downloads/virtualize/parasoft_soavirt_server_9.10.4.zip

And the associated `.md5` URLs.

**Comment by mattloveparasoft** [comment]
I opened a trouble ticket with Parasoft IT regarding these download URLs.
I will pass along any status updates.

**Comment by mattloveparasoft** [comment]
The network issues with www1.parasoft.com/downloads has been resolved.
The above links are working for me now.

**Comment by mattloveparasoft** [comment]
Pull request merged to master and updated for the latest version of SOAtest & Virtualize 9.10.5.
